### ISSUE TITLE
reduce queue size to camInstance.buffer_frame_count_-1 , not just by 1 item

### ISSUE THREAD

**Issue by bjudkewitz** [danionella/PyVCAM#3]
In this section where we handle full queues...

https://github.com/danionella/PyVCAM/blob/06f7eee109d5209227b7ff5736c187c4295063d5/src/pyvcam/pvcmodule.cpp#L291-L302

... I believe we should reduce the queue size down to (`camInstance.buffer_frame_count_-1`) , not just by `-1`. Imagine that the system is temporarily overloaded and the queue size grows multiple items beyond `camInstance.buffer_frame_count_`. It has no chance of getting reduced again because a few lines further down we always push one frame back in.  

So I believe we need a while loop
```
if ((int)camInstance.frameQueue_.size() >= camInstance.buffer_frame_count_) { 
   int n_dropped = 0
    while ((int)camInstance.frameQueue_.size() >= camInstance.buffer_frame_count_) { 
        camInstance.frameQueue_.pop(); 
        n_dropped++
    }
    printf("Dropped %zd frame(s)\n", n_dropped); 
}
```

**Comment by johandinox** [comment]
Yes, that's safer!
